Repository AI-Makes-IT/VTP, pull requests merged in 2023-04, with the labels that each got.

#113 #84 Add tasks page
  client/src/App.js
  client/src/components/Navigation.js
  client/src/components/TaskPage/AddStepDialog.js
  client/src/components/TaskPage/AddTaskDialog.js
  client/src/components/TaskPage/FirstTable.js
  client/src/components/TaskPage/SecondTable.js
  client/src/components/TaskPage/StepsTable.js
  client/src/components/TaskPage/TaskPage.js
  client/src/components/TaskPage/ThirdTable.js
  client/src/contexts/StepPopupContext.js
  client/src/locales/en/translation.json
  client/src/locales/fi/translation.json
  client/src/services/TaskService.js
Labels: Sprint 4

#116 Expand tests for subjects, fix routes' return types
  backend/inspection_subjects.js
  backend/test/inspection_subjects.test.js
Labels: Sprint 5

#119 Update inspection information tests & routes
  backend/inspection_information.js
  backend/test/inspection_information.test.js
Labels: Sprint 5

#125 Modify the inspection view to show tables correctly
  client/src/components/InspectionInformation.css
  client/src/components/LatestDocuments.css
  client/src/components/TargetTimeframe.css
Labels: Sprint 5

#134 Update Tests for Drafts API and Fix Route Queries
  backend/drafts.js
  backend/test/drafts.spec.js
  init-scripts/init-script.sql
Labels: Sprint 5

#138 Fix failing Mocha test for retrieving all drafts of an inspection subject
  backend/test/inspection_subjects.test.js
Labels: bug, Sprint 5

#148 Fix homepage link and fetching drafts at home page
  client/src/components/Homepage.js
  client/src/components/Navigation.js
Labels: Sprint 5
